### ISSUE TITLE
Enable comments in .jenkins file

### ISSUE THREAD

**Issue by szalapski** [alefragnani/vscode-jenkins-status#26]
Could you somehow enable us to add comments in the .jenkins file?  Currently, it seems like any invalid characters cause Jenkins Status to fail silently.

**Comment by alefragnani** [comment]
Do you mean as a "new attribute", like:

```json
{
    "url": "http://127.0.0.1:8080/job/myproject",
    "username": "jenkins_user",
    "password": "jenkins_password_or_token",
    "comment": "Any comment we want"
}
```

That would be easy to do, but I don't think this would be _effective_.

I'm thinking that move from `JSON` to `YAML` files would be a better approach. YAML allows _comments_, and is better suited for configuration files, like below. Maybe #11 and #16 would also benefit from this.

```yaml
# Any comment we want
url: http://127.0.0.1:8080/job/myproject
username: jenkins_user
password: jenkins_password_or_token
```

I don't remember why I decided to use JSON in the first place. Probably because the simplicity of `JSON.parse` 🤔 .

What do you think?
